"""adjust directions table

Revision ID: 04f068548764
Revises: ab367670dc43
Create Date: 2024-01-18 20:20:23.057178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f068548764'
down_revision = 'ab367670dc43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('step', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directions', 'step')
    # ### end Alembic commands ###